name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      # TODO: - run: pnpm build
      # TODO: - run: pnpm check
      # TODO: Replace with `- run: pnpm lint`.
      - run: pnpm prettier --plugin-search-dir . --check .
